name: Build & Deploy Tasky

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy-tasky:
    name: Build & Deploy Tasky
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}



      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "${{ secrets.ECR_REPO }}" \
            || aws ecr create-repository --repository-name "${{ secrets.ECR_REPO }}"

      - name: Build & tag Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          # build from the docker/tasky-main directory
          docker build \
            -f docker/tasky-main/Dockerfile \
            -t tasky-app:$IMAGE_TAG \
            docker/tasky-main

          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          REPO_NAME=${{ secrets.ECR_REPO }}
          docker tag tasky-app:$IMAGE_TAG \
            $REGISTRY/$REPO_NAME:$IMAGE_TAG

      - name: Push to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          REPO_NAME=${{ secrets.ECR_REPO }}
          docker push $REGISTRY/$REPO_NAME:$IMAGE_TAG

      - name: Debug Docker & ECR state
        run: |
          echo "=== Local Docker images ==="
          docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.ID}}"

          echo "=== ECR repos ==="
          aws ecr describe-repositories --output table

          echo "=== ECR images in $REPO ==="
          aws ecr describe-images --repository-name "${{ secrets.ECR_REPO }}" \
            --query 'imageDetails[].imageTags' --output table
      - name: Debug EKS Nodes
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }} --region ${{ secrets.AWS_DEFAULT_REGION }}
          echo "=== AWS EKS Nodegroups ==="
          aws eks list-nodegroups --cluster-name ${{ secrets.EKS_CLUSTER }} --output table

          echo "=== Kubernetes nodes ==="
          kubectl get nodes -o wide || echo "No nodes registered in Kubernetes"

      - name: Configure kubectl for EKS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name "${{ secrets.EKS_CLUSTER }}" \
            --region "${{ secrets.AWS_DEFAULT_REGION }}"
          
      - name: Update Kubernetes Deployment Image
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }} --region ${{ secrets.AWS_DEFAULT_REGION }}

          IMAGE_TAG=${{ github.sha }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          REPO_NAME=${{ secrets.ECR_REPO }}

          kubectl set image deployment/tasky \
            tasky=$REGISTRY/$REPO_NAME:$IMAGE_TAG \
            --record

          kubectl apply -f k8s/alb-sa.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/admin-binding.yaml

          # *** Replace the sed hack with an explicit set-image ***
          kubectl set image deployment/tasky \
            tasky=$REGISTRY/$REPO_NAME:$IMAGE_TAG \
            --record

      - name: Debug deployed image
        run: |
          echo "Now pulling image =" \
            $(kubectl get deployment tasky -o=jsonpath='{.spec.template.spec.containers[0].image}')

      - name: Validate wizexercise.txt
        run: |
          # wait for your pod to actually be Scheduled and Running
          kubectl wait --for=condition=Ready pod -l app=tasky --timeout=120s
          POD=$(kubectl get pods -l app=tasky -o jsonpath="{.items[0].metadata.name}")
          echo "Containers in pod:" \
            $(kubectl get pod $POD -o jsonpath="{.spec.containers[*].name}")
          PRIMARY_CONTAINER=$(kubectl get pod $POD -o jsonpath="{.spec.containers[0].name}")
          echo "Using container: $PRIMARY_CONTAINER"
          kubectl exec -c "$PRIMARY_CONTAINER" "$POD" -- cat /wizexercise.txt