name: "Tasky App Deployment"

on:
  push:
    branches:
      - main #temporarily adding trigger to main for debugging purposes
    # branches: ["main"]
    # paths:
    #   - 'tasky/**'
    #   - 'docker/**'
    #   - 'k8s/**'
    #   - 'Dockerfile'
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: Build & Deploy Tasky
    runs-on: ubuntu-latest
    # Removed: environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        id: build-image
        run: |
          IMAGE_REPO_NAME=tasky-app
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build \
            -t $IMAGE_REPO_NAME:$IMAGE_TAG \
            -f ./docker/Dockerfile .
          echo "::set-output name=IMAGE::$IMAGE_REPO_NAME:$IMAGE_TAG"

      - name: Tag Docker Image for ECR
        id: tag-image
        run: |
          IMAGE_REPO_NAME=tasky-app
          IMAGE_TAG=${GITHUB_SHA::8}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          FULL_TAG=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $FULL_TAG
          echo "::set-output name=FULL_IMAGE::$FULL_TAG"

      - name: Push to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          FULL_TAG=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/tasky-app:${GITHUB_SHA::8}
          docker push $FULL_TAG

      - name: Update Kubernetes Deployment (kubectl set image)
        env:
          EKS_CLUSTER: wizex-eks-cluster
          AWS_REGION: us-west-2
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          FULL_TAG=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/tasky-app:${GITHUB_SHA::8}

          # Update kubeconfig for EKS
          aws eks update-kubeconfig --name $EKS_CLUSTER --region $AWS_REGION

          # Patch Deployment “tasky” to use the new image
          kubectl set image deployment/tasky tasky-container=$FULL_TAG -n default