name: "Infrastructure Building"

on: [ push, pull_request ]

env:
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: "1.5.5" }
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}
      - run: terraform init -input=false
      - run: terraform validate

  terraform-fmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: "1.5.5" }
      - run: terraform fmt -recursive

  terraform-plan:
    needs: [ terraform-validate ]  # only after validate passes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: "1.5.5" }
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}
      - name: Install SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
      - name: Terraform Plan
        env:
          TF_VAR_ssh_private_key_path: $HOME/.ssh/id_rsa
        run: |
          terraform init -input=false
          terraform plan -out=tfplan.binary
          terraform show -no-color tfplan.binary > tfplan.txt
      - uses: actions/upload-artifact@v4
        if: github.event_name != 'push'
        with:
          name: terraform-plan
          path: terraform/tfplan.txt

  terraform-apply:
    needs: [ terraform-plan ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: "1.5.5" }
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}
      - name: Install SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
      - name: Terraform Init
        run: terraform init -input=false -reconfigure
      - name: Terraform Apply
        env:
          TF_VAR_ssh_private_key_path: $HOME/.ssh/id_rsa
        run: terraform apply -auto-approve